services:
  php:
    restart: always
    container_name: php_${PROJECT_NAME}
    build:
      context: ./
      dockerfile: docker/configs/php/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
    environment:
      WORKDIR: ${WORKDIR}
      PHP_IDE_CONFIG: serverName=tradeHistory
    volumes:
      - ./:${WORKDIR}
    networks:
      - tradehistory_network

  postgres:
    restart: always
    image: postgres:17
    container_name: postgres_${PROJECT_NAME}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD:-rootpass}
      POSTGRES_DB: ${POSTGRES_DB:-project_db}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - tradehistory_network

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx_${PROJECT_NAME}
    environment:
      WORKDIR: ${WORKDIR}
      HTTP_PORT: ${HTTP_PORT}
      HTTPS_PORT: ${HTTPS_PORT}
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./:${WORKDIR}
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./docker/configs/nginx/project.conf.template:/etc/nginx/templates/project.conf.template
      - ./logs/nginx:/var/log/nginx
      - ./logs/cache:/var/cache/nginx
    networks:
      - tradehistory_network

volumes:
  database:

networks:
  tradehistory_network:
    driver: bridge
