FROM php:8.1-fpm
WORKDIR ${WORKDIR}

RUN apt-get -y update && apt-get -y install git unzip rsync

RUN git config --global user.email "bisix21@gmail.com"
RUN git config --global user.name "Bisix21"

ENV TERM xterm-256color

RUN php -r "readfile('https://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer
ENTRYPOINT /bin/bash ${WORKDIR}/docker/configs/php/symfony_install.sh

CMD php-fpm
EXPOSE 9000